namespace: milvus

attu:
  image: "zilliz/attu:v2.2.6"
  port: 3000
  name: attu
  service:
    port: 3000

etcd:
  image: "quay.io/coreos/etcd:v3.5.5"
  port: 2379
  name: etcd
  service:
    port: 2379

milvus:
  image: "milvusdb/milvus:v2.2.11"
  grpcPort: 19530
  httpPort: 9091
  etcdEndpoints: "etcd:2379"
  minioAddress: "minio:9000"
  name: milvus-standalone
  service:
    grpcPort: 19530
    httpPort: 9091

minio:
  image: "minio/minio:RELEASE.2023-03-20T20-16-18Z"
  port: 9000
  accessKey: "minioadmin"
  secretKey: "minioadmin"
  name: minio
  service:
    port: 9000
