apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: milvus
spec:
  type: NodePort
  ports:
    - name: client
      port: {{ .Values.etcd.service.port }}
      nodePort: {{ .Values.etcd.service.nodePort }}
  selector:
    app: etcd
