apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: milvus
spec:
  type: ClusterIP
  ports:
    - name: client
      port: {{ .Values.etcd.service.port }}
      targetPort: {{ .Values.etcd.targetPort }}
  selector:
    app: etcd
