apiVersion: v1
kind: Service
metadata:
  name: milvus-standalone
  namespace: milvus
spec:
  type: NodePort
  ports:
    - name: grpc
      port: {{ .Values.milvus.grpcPort }}
      nodePort: 30003
    - name: http
      port: {{ .Values.milvus.httpPort }}
      nodePort: 30004
  selector:
    app: milvus
