apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: milvus
spec:
  type: ClusterIP
  ports:
    - name: minio
      port: {{ .Values.minio.service.port }}
      targetPort: {{ .Values.minio.targetPort }}
  selector:
    app: minio
