apiVersion: v1
kind: Service
metadata:
  name: milvus-standalone
  namespace: milvus
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: {{ .Values.milvus.grpcPort }}
      targetPort: {{ .Values.milvus.grpcTargetPort }}
    - name: http
      port: {{ .Values.milvus.httpPort }}
      targetPort: {{ .Values.milvus.httpTargetPort }}
  selector:
    app: milvus
