apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: milvus
spec:
  type: NodePort
  ports:
    - name: minio
      port: {{ .Values.minio.service.port }}
      nodePort: {{ .Values.minio.service.nodePort }}
  selector:
    app: minio
