apiVersion: v1
kind: Service
metadata:
  name: attu
  namespace: milvus
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: {{ .Values.attu.service.port }}
      targetPort: {{ .Values.attu.port }}
      nodePort: {{ .Values.attu.service.nodePort }}
  selector:
    app: attu
